name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
