name: Python CI

# Run this workflow every time a new commit pushed to your repository
on:
  - push
  - pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
