name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: pip install poetry
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: make lint
